### ISSUE TITLE
Not working for me so far

### ISSUE THREAD

**Issue by phdsigns** [Jakiboy/Fantazy-Sidebar#1]
Hello Jakiboy,

Just installed the plugin...
"Fantazy Sidebar is loaded ok" however, options do not get updated...
After saving the changes, shouldn't the following files show the changes?
contentID: '#content',
sidebarID: '#sidebar',
waitingTime: 3000,
debounce: 500,
animate: 3000,
offsetTop: 0,
offsetBottom: 0,
minHDiff: 0

Let me know,
Best Regards,
PhD

**Comment by Jakiboy** [comment]
Hey Mr <strong>PhD</strong>,thanks for ur Review, so ... i just findout that i had a problem during <strong>updating</strong> the plugin , now, i resolved the issue ,..i commit changes in Main.php
& im working on a new version that w'll <stong>works perfectly</strong>
ur suggestions are welcome
Best Regards
Jb
