### ISSUE TITLE
Fantasy sidebar issue

### ISSUE THREAD

**Issue by noirebene** [Jakiboy/Fantazy-Sidebar#3]
Hi 
I ve installed WP Deferred Javascript and fatally sidebar dont works, have you an idea how to fix this issue ?
https://wordpress.org/plugins/wp-deferred-javascripts/

Many thx
Phil

**Comment by Jakiboy** [comment]
Hey, 
this plugin defer the loading of nessasary JavaScripts (**jQuery** & **wp-fantazy-sidebar.js**) after Fantazy sidebar script who controlle the sidebar !
to resolve the probleme you have to **add an exception to WP Deferred** : of this two files : 
https://your-domaine.com/wp-includes/js/jquery/jquery.js
https://your-domaine.com/wp-content/plugins/fantazy-sidebar/core/js/wp-fantazy-sidebar.js

Make sure of links.
Have a good day 👍
JS

**Comment by noirebene** [comment]
Opus sorry,

Here is the link of the plugin Fantasy Sidebar who doesn't works with wp-deferred- javascript
https://wordpress.org/plugins/fantazy-sidebar/

**Comment by Jakiboy** [comment]
I mean : 
![12456](https://user-images.githubusercontent.com/7604550/32121201-89b6dd62-bb53-11e7-91b7-f4e15381189e.jpg)

thats the solution :)

**Comment by noirebene** [comment]
Great ! Works like a charm !

Many thx
